# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdf1e9609b8f327bebe66ada82c11784b3c845aa11fb64a122944cff29c86b8584a0ce3cab851513c8c59f06b87b7cccd6988747e53936bbb2f8ee0e138e4722

test:
  secret_key_base: 2778bedcb3358db4d5d8c908c4eacacc3957477e01b6e3f9f1b85070d0f0da7a55fa062ca80ca2dedc957869a5cf2922140ed2975190fc9cb3bb2528d5a7a762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
